firesim_gemmini_rerocc_pairmanager_dummy8x8_4c12p12_sbus64_cfg32_nic_notrace:
    agfi: agfi-077451484fe3b63c3
    driver_tar: /home/ubuntu/chipyard/tmp/firesim-aws-f2/driver-bundles/agfi077451-dummy8x8-sbus64-cfg32-nic-notrace-20260507/driver-bundle.tar.gz
    deploy_quintuplet_override: null
    custom_runtime_config: null
