include $(abs_top_srcdir)/Makefrag

tests = \
	template \
	spad \
	bw_test \
	bw_test_gemmini \
	bw_test_mt_gemmini \
	bw_test_direct_gemmini \
	bw_test_direct_gemmini_noc \
	bw_test_direct_gemmini_noc_abtest \
	latency_test \
	mt_hello \
	rerocc_lc_matrix_baremetal \
	rerocc_lc_resadd_explicit_interleaved \
	rerocc_lc_bias_mvin3_runtime_alias_focus \
	rerocc_lc_pointwise_os_first_pair_runtime_alias_focus \
	rerocc_lc_pointwise_os_inner_runtime_alias_focus \
	rerocc_lc_pointwise_stage0_runtime_interleaved_focus \
	mvin_mvout \
	mvin_mvout_zeros \
	mvin_mvout_stride \
	mvin_mvout_block_stride \
	mvin_mvout_acc \
	mvin_mvout_acc_zero_stride \
	mvin_mvout_acc_stride \
	mvin_mvout_acc_full \
	mvin_mvout_acc_full_stride \
	matmul_os \
	matmul_ws \
	matmul \
	raw_hazard \
	aligned \
	padded \
	mvin_scale \
	conv \
	conv_stride \
	conv_rect \
	conv_rect_pool \
	conv_with_pool \
	conv_with_rot180 \
	conv_with_kernel_dilation \
	conv_with_input_dilation \
	conv_with_input_dilation_and_rot180 \
	conv_with_input_dilation_and_neg_padding \
	conv_trans_output_1203 \
	conv_trans_weight_1203 \
	conv_trans_weight_0132 \
	conv_trans_input_3120 \
	conv_trans_input_3120_with_kernel_dilation \
	conv_first_layer \
	conv_dw \
	conv_perf \
	conv_dw_perf \
	tiled_matmul_os \
	tiled_matmul_ws \
	tiled_matmul_ws_At \
	tiled_matmul_ws_Bt \
	tiled_matmul_ws_full_C \
	tiled_matmul_ws_low_D \
	tiled_matmul_ws_igelu \
	tiled_matmul_ws_layernorm \
	tiled_matmul_ws_softmax \
	tiled_matmul_ws_perf \
	tiled_matmul_cpu \
	tiled_matmul_option \
	transpose \
	matrix_add \
	resadd \
	resadd_stride \
	global_average \
	gemmini_counter \

tests_baremetal = $(tests:=-baremetal)

ifeq ($(findstring spike,$(RUNNER)),spike)
# Currently don't support conv or conv-with-pool on spike
runs_baremetal = $(addsuffix .run,$(filter-out conv-baremetal conv_with_pool-baremetal,$(tests_baremetal)))
else
# Don't run very long benchmarks for RTL sim
runs_baremetal = $(addsuffix .run,$(filter-out tiled_matmul_cpu-baremetal tiled_matmul_option-baremetal,$(tests_baremetal)))
endif

ifdef BAREMETAL_ONLY
tests_linux =
tests_pk =
else
tests_linux = $(tests:=-linux)
tests_pk = $(tests:=-pk)
endif

# CTH: Copied `riscv-tests/benchmarks/common` to 
#      `riscv-tests-benchmarks-common` under the folder of this script. 
#      Modified the `crt.S` to correctly support multiple threads.
# BENCH_COMMON = $(abs_top_srcdir)/riscv-tests/benchmarks/common
BENCH_COMMON = $(abs_top_srcdir)/riscv-tests-benchmarks-common

GEMMINI_HEADERS = $(abs_top_srcdir)/include/gemmini.h $(abs_top_srcdir)/include/gemmini_params.h $(abs_top_srcdir)/include/gemmini_testutils.h

# CTH: set env var `GEMMINI_NUM_CPU_CORES` according to the Chipyard config
ifeq ($(strip $(GEMMINI_NUM_CPU_CORES)),)
$(warning env var `GEMMINI_NUM_CPU_CORES` not set; defaulting to 1)
GEMMINI_NUM_CPU_CORES := 1
endif

EXTRA_CFLAGS ?=

CFLAGS := $(CFLAGS) \
	-DPREALLOCATE=1 \
	-DMULTITHREAD=1 \
	-mcmodel=medany \
	-std=gnu99 \
	-O2 \
	-ffast-math \
	-fno-common \
	-fno-builtin-printf \
	-fno-tree-loop-distribute-patterns \
	-march=rv64gc -Wa,-march=rv64gc \
	-lm \
	-lgcc \
	-I$(abs_top_srcdir)/riscv-tests \
	-I$(abs_top_srcdir)/riscv-tests/env \
	-I$(abs_top_srcdir) \
	-I$(BENCH_COMMON) \
	-DID_STRING=$(ID_STRING) \
	-DPRINT_TILE=0 \
	-DNUM_CORES=$(GEMMINI_NUM_CPU_CORES) \
	$(EXTRA_CFLAGS) \

CFLAGS_PK := \
	$(CFLAGS) \
	-static \
	-DBAREMETAL=1 \

CFLAGS_BAREMETAL := \
	$(CFLAGS) \
	-nostdlib \
	-nostartfiles \
	-static \
	-T $(BENCH_COMMON)/test.ld \
	-DBAREMETAL=1 \

all: $(tests_baremetal) $(tests_linux) $(tests_pk)

vpath %.c $(src_dir) $(src_dir)/learn-gemmini $(src_dir)/original

%-baremetal: %.c $(GEMMINI_HEADERS)
	$(CC_BAREMETAL) $(CFLAGS_BAREMETAL) $< $(LFLAGS) -o $@ \
		$(wildcard $(BENCH_COMMON)/*.c) $(wildcard $(BENCH_COMMON)/*.S) $(LIBS)

%-linux: %.c $(GEMMINI_HEADERS)
	$(CC_LINUX) $(CFLAGS) $< $(LFLAGS) -o $@

%-pk: %.c $(GEMMINI_HEADERS)
	$(CC_LINUX) $(CFLAGS_PK) $< $(LFLAGS) -o $@

run-baremetal: $(runs_baremetal)

%-baremetal.run: %-baremetal
	$(RUNNER)$(abs_top_srcdir)/build/bareMetalC/$^

junk += $(tests_baremetal) $(tests_linux) $(tests_pk)
