#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export PIPELINE_RUNTIME_FIRESIM_TRACERV_WORKER_MARKERS="${PIPELINE_RUNTIME_FIRESIM_TRACERV_WORKER_MARKERS:-1}"
export PIPELINE_RUNTIME_RUNNER_BIN_MAPS_ONCE_ENABLE="${PIPELINE_RUNTIME_RUNNER_BIN_MAPS_ONCE_ENABLE:-1}"
export PIPELINE_RUNTIME_RUNNER_BIN_MAPS_ONCE_TARGET="${PIPELINE_RUNTIME_RUNNER_BIN_MAPS_ONCE_TARGET:-/root/rerocc-linux-tests/pipeline-runtime/rerocc_pipeline_runtime-linux}"
export PIPELINE_RUNTIME_RUNNER_BIN_PROC_POLL_SECONDS="${PIPELINE_RUNTIME_RUNNER_BIN_PROC_POLL_SECONDS:-60}"
export PIPELINE_RUNTIME_RUNNER_PROC_DETAIL_ENABLE="${PIPELINE_RUNTIME_RUNNER_PROC_DETAIL_ENABLE:-1}"
export PIPELINE_RUNTIME_RUNNER_PROC_DETAIL_LABEL_REGEX="${PIPELINE_RUNTIME_RUNNER_PROC_DETAIL_LABEL_REGEX:-after-bin-spawn|bin-delay-probe|after-bin-wait}"
export PIPELINE_RUNTIME_RUNNER_BIN_DELAY_PROBE_ENABLE="${PIPELINE_RUNTIME_RUNNER_BIN_DELAY_PROBE_ENABLE:-1}"
export PIPELINE_RUNTIME_RUNNER_BIN_DELAY_PROBE_DELAYS="${PIPELINE_RUNTIME_RUNNER_BIN_DELAY_PROBE_DELAYS:-10,30,60,180,480,900}"
export PIPELINE_RUNTIME_RUNNER_BIN_DELAY_PROBE_FORCE_SYNC="${PIPELINE_RUNTIME_RUNNER_BIN_DELAY_PROBE_FORCE_SYNC:-1}"
export PIPELINE_RUNTIME_RUNNER_PTRACE_PROBE_ENABLE="${PIPELINE_RUNTIME_RUNNER_PTRACE_PROBE_ENABLE:-1}"
export PIPELINE_RUNTIME_RUNNER_PTRACE_PROBE_TOOL="${PIPELINE_RUNTIME_RUNNER_PTRACE_PROBE_TOOL:-/root/rerocc-linux-tests/rerocc_ptrace_peek-linux}"
export PIPELINE_RUNTIME_RUNNER_PTRACE_PROBE_DETAIL_BYTES="${PIPELINE_RUNTIME_RUNNER_PTRACE_PROBE_DETAIL_BYTES:-32}"
export PAIRDUMMY_TRACERV_SCRIPT_NAME_OVERRIDE="$(basename "${BASH_SOURCE[0]}")"
export PAIRDUMMY_TRACERV_SESSION_PREFIX="${PAIRDUMMY_TRACERV_SESSION_PREFIX:-pairdummy-sbus128-tracerv-workerpc}"
export PAIRDUMMY_TRACERV_DESCRIPTION="${PAIRDUMMY_TRACERV_DESCRIPTION:-Worker-PC-triggered TracerV fallback workflow for the 12-pair sbus128 dummy-model pipeline-runtime path.}"
export PAIRDUMMY_TRACERV_TRIGGER_USAGE_DESC="${PAIRDUMMY_TRACERV_TRIGGER_USAGE_DESC:-enables selector=2 TracerV capture using exact stage_worker_main marker PCs}"
export PAIRDUMMY_TRACERV_SHOW_NOTE="${PAIRDUMMY_TRACERV_SHOW_NOTE:-worker-pc-triggered tracerv via stage_worker_main markers 0x2a2b0 -> 0x2ab22; do-not-infer-entrypoint-from-workload-overlay-root-firemarshal.sh}"
export PAIRDUMMY_TRACERV_SHOW_SELECTOR="${PAIRDUMMY_TRACERV_SHOW_SELECTOR:-2}"
export PAIRDUMMY_TRACERV_SHOW_START_PC="${PAIRDUMMY_TRACERV_SHOW_START_PC:-2a2b0}"
export PAIRDUMMY_TRACERV_SHOW_END_PC="${PAIRDUMMY_TRACERV_SHOW_END_PC:-2ab22}"
export PAIRDUMMY_TRACERV_WORKLOAD_JSON="${PAIRDUMMY_TRACERV_WORKLOAD_JSON:-generators/gemmini/software/gemmini-rocc-tests/rerocc-linux-tests-coupleddma/workload/rerocc-lc-linux-coupleddma-bertmini-pipeline-runtime-batch8-fileonly-sync-pairdummy-tracerv-inst.json}"
export PAIRDUMMY_TRACERV_RUNTIME_CFG="${PAIRDUMMY_TRACERV_RUNTIME_CFG:-/home/ubuntu/chipyard/sims/firesim/deploy/config_runtime_f2_gemmini_rerocc_pairmanager_dummy16x16_4c12p12_sbus128_linux_bertmini_pipeline_runtime_batch8_fileonly_sync_tracerv_workerpc.yaml}"
export PIPELINE_RUNTIME_FIRESIM_TRACERV_WORKER_PC_START_EXPECT="${PIPELINE_RUNTIME_FIRESIM_TRACERV_WORKER_PC_START_EXPECT:-${PAIRDUMMY_TRACERV_SHOW_START_PC}}"
export PIPELINE_RUNTIME_FIRESIM_TRACERV_WORKER_PC_END_EXPECT="${PIPELINE_RUNTIME_FIRESIM_TRACERV_WORKER_PC_END_EXPECT:-${PAIRDUMMY_TRACERV_SHOW_END_PC}}"

# shellcheck disable=SC1091
source "${script_dir}/pairdummy_sbus128_tracerv_workflow.sh"
