#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# 6-pair / 2-core profile for the dummy8x8 sbus64 NIC hardware-debug target.
# This is separate from the older c4_g12 sbus64 profile so FireMarshal images
# carry a target key that matches the AGFI under test.
# shellcheck disable=SC1091
source "${script_dir}/pairdummy_sbus64_dummy8x8_fixed_env.sh"

export PIPELINE_RUNTIME_PROFILE_ID="pairdummy-sbus64-dummy8x8-g6-fixed-v1"
export TARGET_KEY="rerocc_globalnoc_pairmanager_dummy8x8_c2_g6_d6_spad1024kb_dram19_noc64_mac64_sbus64"
export METHODS="${METHODS:-ours2}"
export TARGET_BATCH="${PAIRDUMMY_SBUS64_G6_TARGET_BATCH:-8}"

export NUM_CORES="2"
export NUM_GEMMINI="6"
export NUM_DMA="6"
export GEMMINI_BASE_ID="0"
export DMA_BASE_ID="0"
export PAIR_MANAGER_MODE="1"
export PAGES_PER_ACC="1024"

export PIPELINE_RUNTIME_GDBSERVER_ENABLE="${PIPELINE_RUNTIME_GDBSERVER_ENABLE:-0}"
export PIPELINE_RUNTIME_LOCAL_GDB_ENABLE="${PIPELINE_RUNTIME_LOCAL_GDB_ENABLE:-0}"
export PIPELINE_RUNTIME_GDB_MARKER_ENABLE="${PIPELINE_RUNTIME_GDB_MARKER_ENABLE:-0}"

# Keep the first automated F2 run low-noise and completion-oriented. More
# intrusive trigger or gdbserver overlays should be applied per rerun.
export PIPELINE_RUNTIME_STDIO_CAPTURE_MODE="${PAIRDUMMY_SBUS64_G6_STDIO_CAPTURE_MODE:-uart}"
export PIPELINE_RUNTIME_GUEST_LOG_ENABLE="${PAIRDUMMY_SBUS64_G6_GUEST_LOG_ENABLE:-0}"
export PIPELINE_RUNTIME_GUEST_DEEP_LOG_ENABLE="${PAIRDUMMY_SBUS64_G6_GUEST_DEEP_LOG_ENABLE:-0}"
export PIPELINE_RUNTIME_YAML_LINE_LOG_ENABLE="${PAIRDUMMY_SBUS64_G6_YAML_LINE_LOG_ENABLE:-0}"
export PIPELINE_RUNTIME_AUDIT_LOG_ENABLE="${PAIRDUMMY_SBUS64_G6_AUDIT_LOG_ENABLE:-0}"
export PIPELINE_RUNTIME_CHECKPOINT_LOG_ENABLE="${PAIRDUMMY_SBUS64_G6_CHECKPOINT_LOG_ENABLE:-0}"
export PIPELINE_RUNTIME_BREADCRUMB_ENABLE="${PAIRDUMMY_SBUS64_G6_BREADCRUMB_ENABLE:-0}"
export PIPELINE_RUNTIME_CHILD_PROC_DIAG_ENABLE="${PAIRDUMMY_SBUS64_G6_CHILD_PROC_DIAG_ENABLE:-0}"
export CAPTURE_PERIODIC_SYNC_ENABLE="${PAIRDUMMY_SBUS64_G6_PERIODIC_SYNC_ENABLE:-0}"
export CAPTURE_PROGRESS_PING_ENABLE="${PAIRDUMMY_SBUS64_G6_PROGRESS_PING_ENABLE:-0}"

export FIRESIM_RUNWORKLOAD_IDLE_TIMEOUT_SECONDS="${PAIRDUMMY_SBUS64_G6_IDLE_TIMEOUT_SECONDS:-7200}"
export FIRESIM_RUNWORKLOAD_LIVE_IDLE_TIMEOUT_SECONDS="${PAIRDUMMY_SBUS64_G6_LIVE_IDLE_TIMEOUT_SECONDS:-10800}"
