#!/usr/bin/env bash
set -euo pipefail

# Fixed semantic profile for the 12-pair sbus128 dummy-model bring-up path.
# Do not override these ad hoc in the shell. If this profile needs to change,
# edit this file, rebuild the image, and let freshness checks propagate it.

export PIPELINE_RUNTIME_PROFILE_ID="pairdummy-sbus128-fixed-v26"

export ENABLE_PIPELINE_RUNTIME="1"
export TARGET_KEY="rerocc_globalnoc_pairmanager_dummy16x16_c4_g12_d12_spad1024kb_dram19_noc64_mac256_sbus128"
export METHODS="ours2"
export TARGET_BATCH="8"

export NUM_CORES="4"
export NUM_GEMMINI="12"
export NUM_DMA="12"
export GEMMINI_BASE_ID="0"
export DMA_BASE_ID="0"
export PAIR_MANAGER_MODE="1"
export PAGES_PER_ACC="1024"

export DUMMY_GEMMINI_MODE="1"
export PIPELINE_RUNTIME_SKIP_MODEL_BIN_LOAD="1"
export PIPELINE_RUNTIME_SKIP_INPUT_LOAD="1"
export PIPELINE_RUNTIME_SKIP_GOLDEN_CHECK="1"

export PIPELINE_RUNTIME_PROGRESS="1"
export PIPELINE_RUNTIME_PROGRESS_RAW="0"
export PIPELINE_RUNTIME_PROGRESS_HOT="0"
export PIPELINE_RUNTIME_ONLY_MARKER="0"
export PIPELINE_RUNTIME_GEMMINI_PHASE="0"
export PIPELINE_RUNTIME_CRITICAL_UART_PROBE="0"
export PIPELINE_RUNTIME_CRITICAL_UART_PAD_BURST="0"
export PIPELINE_RUNTIME_PROGRESS_PAD_BURST="0"
export PIPELINE_RUNTIME_MLOCKALL_MODE="2"

export PIPELINE_RUNTIME_LOG_PROFILE="coarse"
export PIPELINE_RUNTIME_STDIO_CAPTURE_MODE="log"
export PIPELINE_RUNTIME_UART_LOG_ENABLE="0"
export PIPELINE_RUNTIME_GUEST_LOG_ENABLE="1"
export PIPELINE_RUNTIME_GUEST_DEEP_LOG_ENABLE="0"
export PIPELINE_RUNTIME_AUDIT_LOG_ENABLE="0"
export PIPELINE_RUNTIME_CHECKPOINT_LOG_ENABLE="0"
export PIPELINE_RUNTIME_CHECKPOINT_LOG_PATH="/root/pipeline-runtime-debug/bertmini-batch8.checkpoint.log"
export PIPELINE_RUNTIME_RUNNER_STAGE_SYNC_ENABLE="0"
export PIPELINE_RUNTIME_DISABLE_MAPPING_CACHE="1"
export PIPELINE_RUNTIME_DMA_SUBMIT_TRACE_ENABLE="0"
export PIPELINE_RUNTIME_DMA_FORCE_DIRECT_ENABLE="${PIPELINE_RUNTIME_DMA_FORCE_DIRECT_ENABLE-1}"
export PIPELINE_RUNTIME_DMA_BLOCKING_WAIT_POLL_TIMEOUT_ENABLE="${PIPELINE_RUNTIME_DMA_BLOCKING_WAIT_POLL_TIMEOUT_ENABLE-1}"
export PIPELINE_RUNTIME_DMA_BOUNCE_BYPASS_ENABLE="${PIPELINE_RUNTIME_DMA_BOUNCE_BYPASS_ENABLE-0}"
# Low-perturbation baseline.
# Export proof probes must stay off here; later rounds may only add temporary
# trigger overlays via PIPELINE_RUNTIME_DEBUG_TRIGGER_*.
# Keep the sparse export page window pinned to a non-matching sentinel. Leaving
# PAGE_START/PAGE_END unset falls back to the built-in sparse page pattern and
# re-enables hot-path page logs for tensor=2 export.
export PIPELINE_RUNTIME_DMA_EXPORT_PROBE_ENABLE="0"
export PIPELINE_RUNTIME_DMA_EXPORT_PROBE_TOKEN_START=""
export PIPELINE_RUNTIME_DMA_EXPORT_PROBE_TOKEN_END=""
export PIPELINE_RUNTIME_DMA_EXPORT_PAGE_START="4294967295"
export PIPELINE_RUNTIME_DMA_EXPORT_PAGE_END="4294967295"
export PIPELINE_RUNTIME_DMA_FIXED_LOAD_PROBE_ENABLE="0"
export PIPELINE_RUNTIME_DMA_FIXED_LOAD_MONITOR_PROBE_ENABLE="0"
export PIPELINE_RUNTIME_DMA_FIXED_LOAD_PRE_SRC_NOPS="0"
export PIPELINE_RUNTIME_DMA_FIXED_LOAD_PROBE_STAGE_ID="0"
export PIPELINE_RUNTIME_DMA_FIXED_LOAD_PROBE_TENSOR_ID="0"
export PIPELINE_RUNTIME_DMA_FIXED_LOAD_PROBE_TOKEN_START=""
export PIPELINE_RUNTIME_DMA_FIXED_LOAD_PROBE_TOKEN_END=""
export PIPELINE_RUNTIME_DMA_FIXED_LOAD_PAGE_START="0"
export PIPELINE_RUNTIME_DMA_FIXED_LOAD_PAGE_END="0"
export PIPELINE_RUNTIME_DMA_FIXED_LOAD_CHECKPOINT_ENABLE="0"
export PIPELINE_RUNTIME_BREADCRUMB_ENABLE="${PIPELINE_RUNTIME_BREADCRUMB_ENABLE-1}"
export PIPELINE_RUNTIME_BREADCRUMB_PATH="${PIPELINE_RUNTIME_BREADCRUMB_PATH-/root/pipeline-runtime-debug/bertmini-batch8.breadcrumb.bin}"
export PIPELINE_RUNTIME_BREADCRUMB_SEGMENT="${PIPELINE_RUNTIME_BREADCRUMB_SEGMENT-0}"
export PIPELINE_RUNTIME_BREADCRUMB_GLOBAL_STAGE="${PIPELINE_RUNTIME_BREADCRUMB_GLOBAL_STAGE-0}"
export PIPELINE_RUNTIME_BREADCRUMB_LOCAL_STAGE="${PIPELINE_RUNTIME_BREADCRUMB_LOCAL_STAGE-0}"
export PIPELINE_RUNTIME_BREADCRUMB_SUBBATCH="${PIPELINE_RUNTIME_BREADCRUMB_SUBBATCH-}"
export PIPELINE_RUNTIME_BREADCRUMB_STAGE_RADIUS="${PIPELINE_RUNTIME_BREADCRUMB_STAGE_RADIUS-0}"
export PIPELINE_RUNTIME_BREADCRUMB_SUBBATCH_RADIUS="${PIPELINE_RUNTIME_BREADCRUMB_SUBBATCH_RADIUS-0}"
# Narrow exception to the fixed-profile rule: a single rerun may overlay only
# the selected breadcrumb filters below and the trigger-gated debug selectors.
export PIPELINE_RUNTIME_DEBUG_TRIGGER_ENABLE="${PIPELINE_RUNTIME_DEBUG_TRIGGER_ENABLE-0}"
export PIPELINE_RUNTIME_DEBUG_TRIGGER_KIND="${PIPELINE_RUNTIME_DEBUG_TRIGGER_KIND-}"
export PIPELINE_RUNTIME_DEBUG_TRIGGER_SEGMENT="${PIPELINE_RUNTIME_DEBUG_TRIGGER_SEGMENT-0}"
export PIPELINE_RUNTIME_DEBUG_TRIGGER_GLOBAL_STAGE="${PIPELINE_RUNTIME_DEBUG_TRIGGER_GLOBAL_STAGE-0}"
export PIPELINE_RUNTIME_DEBUG_TRIGGER_LOCAL_STAGE="${PIPELINE_RUNTIME_DEBUG_TRIGGER_LOCAL_STAGE-0}"
export PIPELINE_RUNTIME_DEBUG_TRIGGER_SUBBATCH="${PIPELINE_RUNTIME_DEBUG_TRIGGER_SUBBATCH-}"
export PIPELINE_RUNTIME_DEBUG_TRIGGER_MANAGER="${PIPELINE_RUNTIME_DEBUG_TRIGGER_MANAGER-}"
export PIPELINE_RUNTIME_DEBUG_TRIGGER_TENSOR_ID="${PIPELINE_RUNTIME_DEBUG_TRIGGER_TENSOR_ID-}"
export PIPELINE_RUNTIME_DEBUG_TRIGGER_PAGE="${PIPELINE_RUNTIME_DEBUG_TRIGGER_PAGE-}"
export PIPELINE_RUNTIME_DEBUG_TRIGGER_TOKEN="${PIPELINE_RUNTIME_DEBUG_TRIGGER_TOKEN-}"
export PIPELINE_RUNTIME_DEBUG_TRIGGER_PRE_RING="${PIPELINE_RUNTIME_DEBUG_TRIGGER_PRE_RING-8}"
export PIPELINE_RUNTIME_DEBUG_TRIGGER_POST_BUDGET="${PIPELINE_RUNTIME_DEBUG_TRIGGER_POST_BUDGET-32}"
export PIPELINE_RUNTIME_DEBUG_TRIGGER_MATCH_ONCE="${PIPELINE_RUNTIME_DEBUG_TRIGGER_MATCH_ONCE-1}"
export PIPELINE_RUNTIME_DEBUG_TRIGGER_LOG_PATH="${PIPELINE_RUNTIME_DEBUG_TRIGGER_LOG_PATH-/root/pipeline-runtime-debug/bertmini-batch8.trigger.log}"

# Pairdummy pipeline-runtime runs often enter a stable "heartbeat alive but
# guest-visible progress frozen" plateau. Keep the short 600s idle timeout, but
# cap the heartbeat-live extension to 1 hour so converged stalls are reclaimed
# promptly without changing the global FireSim watchdog behavior.
export FIRESIM_RUNWORKLOAD_LIVE_IDLE_TIMEOUT_SECONDS="${FIRESIM_RUNWORKLOAD_LIVE_IDLE_TIMEOUT_SECONDS:-3600}"

export WATCHDOG_MS="600000"
export EXPORT_DMA_TIMEOUT_MS="${EXPORT_DMA_TIMEOUT_MS-5000}"
export TRACE_ENABLE="0"
export GOLDEN_CHECK_ENABLE="0"
export DEEP_LOG_ENABLE="0"

export CAPTURE_AUTO_POWEROFF="1"
export CAPTURE_PERIODIC_SYNC_ENABLE="1"
export CAPTURE_PERIODIC_SYNC_SECONDS="1"
export CAPTURE_PROGRESS_PING_ENABLE="0"
export CAPTURE_PROGRESS_PING_SECONDS="30"

export HUGETLB_PAGES="1"
export HUGETLB_MOUNT="/dev/hugepages"

unset PIPELINE_RUNTIME_MAPPING_CACHE_PROBE_START || true
unset PIPELINE_RUNTIME_MAPPING_CACHE_PROBE_END || true
unset PIPELINE_RUNTIME_MAPPING_PARSE_PROGRESS_INTERVAL || true
unset PIPELINE_RUNTIME_MAPPING_PARSE_PROBE_START || true
unset PIPELINE_RUNTIME_MAPPING_PARSE_PROBE_END || true
unset DEEP_LOG_SEGMENT || true
unset DEEP_LOG_GLOBAL_STAGE || true
unset DEEP_LOG_LOCAL_STAGE || true
unset DEEP_LOG_SUBBATCH || true
unset DEEP_LOG_STAGE_RADIUS || true
unset DEEP_LOG_SUBBATCH_RADIUS || true
