#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export ENABLE_PIPELINE_RUNTIME="${ENABLE_PIPELINE_RUNTIME:-1}"
export DUMMY_GEMMINI_MODE="${DUMMY_GEMMINI_MODE:-0}"
export PIPELINE_RUNTIME_PROGRESS="${PIPELINE_RUNTIME_PROGRESS:-1}"
export PIPELINE_RUNTIME_PROGRESS_RAW="${PIPELINE_RUNTIME_PROGRESS_RAW:-0}"
export PIPELINE_RUNTIME_PROGRESS_HOT="${PIPELINE_RUNTIME_PROGRESS_HOT:-0}"
export PIPELINE_RUNTIME_ONLY_MARKER="${PIPELINE_RUNTIME_ONLY_MARKER:-1}"

exec "${SCRIPT_DIR}/host-init.sh"
