#!/bin/sh
set -eu

export NUM_GEMMINI="${NUM_GEMMINI:-1}"
export NUM_DMA="${NUM_DMA:-1}"
export DMA_BASE_ID="${DMA_BASE_ID:-0}"
export UARTPROBE_DMA_MANAGER_ID="${UARTPROBE_DMA_MANAGER_ID:-0}"
export UARTPROBE_BYTES="${UARTPROBE_BYTES:-4096}"
export UARTPROBE_REPEAT_COUNT="${UARTPROBE_REPEAT_COUNT:-2}"
export UARTPROBE_OBSERVABILITY="${UARTPROBE_OBSERVABILITY:-full}"
export UARTPROBE_PROC_DIAG_ENABLE="${UARTPROBE_PROC_DIAG_ENABLE:-1}"
export UARTPROBE_PROC_DIAG_POLLS="${UARTPROBE_PROC_DIAG_POLLS:-30}"
export UARTPROBE_PROC_DIAG_SLEEP_SECONDS="${UARTPROBE_PROC_DIAG_SLEEP_SECONDS:-1}"
export UARTPROBE_PROC_DIAG_KILL_ON_STUCK="${UARTPROBE_PROC_DIAG_KILL_ON_STUCK:-1}"

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
exec "${SCRIPT_DIR}/run_rerocc_dma_export_alias_uartprobe_filewrite_quiet_capture.sh" "$@"
